var moment = require("moment");
var datetime = moment().format("YYYYMMDDHHmmss");

var user={

testdata_username                                   :"megha.kailas@cloudium.io",//  :"akash.mathew@cloudium.io",
testdata_password                                   :"Passw0rd",
testdata_time_20                                    :"20000",
testdata_time_5                                     :"5000",
testdata_time_8                                     :"8000",
testdata_time_2                                     :"2000",
testdata_time_10                                    :"10000",
testdata_time_1                                     :"1000",
testdata_company_name1                              :"Cloudium",
testdata_update_billing_info                        :"Update Billing Info", 
testdata_MM_innersearch_valid                       :"IPO",
testdata_overview_search                            :"Hospitality",
testdata_Homecity_DD                                :"Home City", 
testdata_Barnes_Noble_Education                     :"Barnes & Noble Education Inc",
testdata_alabama_AL                                 :"AL",
testdata_homecity_Tuscaloosa                        :"Tuscaloosa, AL, USA",
testdata_homecity_Tuscaloosa1                       :"Tuscaloosa",
testdata_40                                         :"40",
testdata_60                                         :"60",
testdata_california                                 :"california",
testdata_invalid_value1                             :"10467",
testdata_invalid_value2                             :"94568",
testdata_company_name                               :"google",
testdata_informationservices                        :"information services",
testdata_professional_school_name                   :"North Haven High School",
testdata_comapany_location                          :"Minneapolis, MN, USA",
testdata_prospectprofile_name                       :"Automation Test"+datetime,
testdata_prospectprofile_name_edit                  :"Automation Test Edit"+datetime,
testdata_prospectprofile_name_duplicate             :"duplicate name"+datetime,
testdata_prospectprofile_name_homecity              :"Automation City Name"+datetime,
testdata_homecity1_Tuscaloosa                       :"Tuscaloosa",
testdata_exactcity_northport                        :"Northport",
testdata_exactcity_northport_verify_on_people       :"Northport",
testdata_prospectprofile_name_state                 :"Automation State Name"+datetime,
testdata_exactcity_AL_verify_on_people              :"AL",
testdata_exactcity_northport_verify_on_event        :"Northport",
testdata_prospectprofile_name_first_degree          :"Automation First Degree"+datetime,
testdata_exact_zip                                  :"Automation Exact"+datetime,
testdata_between_zip                                :"Automation Between"+datetime,
testdata_prospectprofile_name_Second_degree         :"Automation Second Degree"+datetime,
testdata_prospectprofile_name_Age                   :"Automation Age"+datetime,
testdata_prospectprofile_name_AgeExact              :"Automation exact Age"+datetime,
testdata_sexM_filterName                            :"Automation Male"+datetime,
testdata_sexF_filterName                            :"Automation Female"+datetime,
testdata_Maritalstatus_M                            :"Automation Marital Status M"+datetime,
testdata_Maritalstatus_single                       :"Automation Marital Status Single"+datetime,
testdata_child_edu                                  :"Automation child Edu"+datetime,
testdata_child_edu1                                 :"Automation Child Edu1"+datetime,
testdata_child_profile_father                       :"Sharif Khaleel",
testdata_child_edu2                                 :"Automation Child Edu2"+datetime,
testdata_child_profile_father1                      :"Sean Scaringella",
testdata_child_edu3                                 :"Automation Child Edu3"+datetime,
testdata_child_profile_father2                      :"Noah Clauser",
testdata_child_edu4                                 :"Automation Child Edu4"+datetime,
testdata_child_profile_father3                      :"Don Coppersmith",
testdata_Interest                                   :"Automation Interest"+datetime,
testdata_Company                                    :"Automation Company"+datetime,
testdata_title_name                                 :"Automation Title"+datetime,
testdata_school_name                                :"Automation School"+datetime,
testdata_groupby                                    :"Automation GroupBy"+datetime,
testdata_Interest                                   :"Automation Interest"+datetime,
testdata_Company                                    :"Automation Company"+datetime,
testdata_title_name                                 :"Automation Title"+datetime,
testdata_school_name                                :"Automation School"+datetime,
testdata_groupby                                    :"Automation GroupBy"+datetime,
testdata_filterzip1                                 :"11768",
testdata_filterzip2                                 :"11770",
testdata_industrynameAccounting                     :"Accounting",
testdata_previouscompany_name                       :"Cristina Bita",
testdata_job_title_name                             :"President",
testdata_wealthsegment_name                         :"Automation Wealthsegment Name"+datetime,
testdata_eventname_name                             :"Automation Event Name"+datetime,
testdata_value_0M                                   :"0",
testdata_value_50M                                  :"50",
testdata_value_100M                                 :"100",
testdata_value_500M                                 :"500",
testdata_value_1B                                   :"1000",
testdata_fav_search_name                            :"William Schumann",
testdata_fav_search_cmpnyname                       :"Avnet",
testdata_fav_search_title                           :"Member Board of Directors",
testdata_fava_school_Granada_Hills                  :"Granada Hills High School",
testdata_event_company_name                         :"Even",
testdata_Sarah_Morgan_name                          :"Sarah Morgan",
testdata_prospectprofile_name_state1                :"Automation multi state"+datetime,
testdata_filterby_name_marc                         :"Marc Guthrie",
testdata_city_name_mobile                           :"Mobile",
testdata_city_name_NewYork                          :"NEW YORK, NORTH POLE, DC",
testdata_CEO                                        :"CEO",
testdata_groupby1                                   :"Automation GroupBya1"+datetime,
testdata_groupby2                                   :"Automation GroupBya2"+datetime,
testdata_groupby3                                   :"Automation GroupBya3"+datetime,
testdata_groupby4                                   :"Automation GroupBya4"+datetime,
testdata_wealthsegment1_name                        :"Automation Wealthsegment1"+datetime,
testdata_wealthsegment2_name                        :"Automation Wealthsegment2"+datetime,
testdata_wealthsegment3_name                        :"Automation Wealthsegment3"+datetime,
testdata_wealthsegment4_name                        :"Automation Wealthsegment4"+datetime,
testdata_wealthsegment5_name                        :"Automation Wealthsegment5"+datetime,
testdata_wealthsegment6_name                        :"Automation Wealthsegment6"+datetime,
testdata_wealthsegment7_name                        :"Automation Wealthsegment7"+datetime,
testdata_wealthsegment8_name                        :"Automation Wealthsegment8"+datetime,

};
                                         
module.exports=user;
